name: Invio Email Automatico

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Install dependencies
        run: pip install firebase-admin
        
      - name: Run Mailer
        env:
          # Usiamo un nome leggermente diverso per forzare GitHub a rileggere il secret
          SECRET_KEY_FIREBASE: ${{ secrets.FIREBASE_JSON }}
        run: python run_mailer.py
